name: pictures
favicon: null
layout_spectrum: 0.68236
typography_spectrum: 0.98876
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e1e4db'
    - '#0e0e0e'
    - '#48483c'
    - '#6a6a6c'
    - '#8d470b'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose:
  - name: follow
    item: null
    url: null
